name: Generate Metrics Svg
on:
schedule:
- cron: '0 0 * * *' # daily at midnight UTC
workflow_dispatch:


jobs:
generate:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Run metrics generator
uses: lowlighter/metrics@latest
with:
token: ${{ secrets.GITHUB_TOKEN }}
base: header, activity, community, repositories, metadata
plugin_languages: yes


- name: Commit generated metrics
run: |
git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git add github-metrics.svg || true
git commit -m "chore: update github metrics svg" || echo "No changes"
git push || echo "Push failed"